      - name: Fetch Cricket (IPL) News
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://www.cricbuzz.com/rss/ipl-2026/news'
          method: 'GET'
          outputFile: 'data/cricket-news.xml'
